M48
; DRILL file {KiCad 9.0.7} date 2026-04-05T20:44:26-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-05T20:44:26-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X44.86Y20.584
X44.86Y15.584
T2
X-45.4Y30.4
X-45.0Y-40.0
X45.0Y30.0
X45.0Y-40.0
M30
